os: linux
language: android
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API

  licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
   - google-gdk-license-.+

before_script:
  - echo "${GOOGLE_SERVICES}" | base64 --decode > app/google-services.json
  - echo "${LOCAL_PROPERTIES}" | base64 --decode > local.properties

script:
  - ./gradlew ktlintDebugCheck
  - ./gradlew lintDebug
  - ./gradlew assembleDebug

before_deploy:
  - git config --local user.name "ripzery"
  - git config --local user.email "phuchit@omise.co"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: release
  api_key: $GH_AUTH_TOKEN
  file_glob: true
  file: app/build/outputs/apk/debug/*.apk
  skip_cleanup: true
  on:
    tags: true
#    branch: master
