os: linux
language: android
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API

  licenses:
   - android-sdk-preview-license-.+
   - android-sdk-license-.+
   - google-gdk-license-.+

#before_install:
#  - mkdir "$ANDROID_HOME/licenses" || true
#  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
#  - chmod +x gradlew
#  - ./gradlew dependencies || true

before_script:
  - touch local.properties
  - echo "ewallet.verification.signup.prefix=\"$SIGNUP_SUCCESSFUL_DEEPLINK\"" >> local.properties
  - echo "ewallet.baseurl=\"$BASE_URL\"" >> local.properties
  - echo "ewallet.socket.baseurl=\"$SOCKET_BASE_URL\"" >> local.properties
  - echo "ewallet.apikey=\"$API_KEY\"" >> local.properties
  - echo "omg.encrypt.keyAlias=\"$KEY_ALIAS\"" >> local.properties
  - echo "omg.encrypt.iv=\"$KEY_IV\"" >> local.properties

script:
  - ./gradlew clean build
  - ./gradlew assembleDebug

after_script:
  - rm -f local.properties
